# Generated by Django 4.2.2 on 2023-06-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DashboardView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("time_period", models.CharField(max_length=100)),
                (
                    "sheets_url",
                    models.URLField(
                        default="https://www.google.com/search?client=firefox-b-1-d&q=coding+for+dummies",
                        max_length=500,
                    ),
                ),
            ],
        ),
    ]
